spring:
  datasource:
    url: jdbc:mysql://47.113.191.64:3306/flower_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.flower.service.entity
  configuration:
    map-underscore-to-camel-case: true